const express = require('express');
const rateLimit = require('express-rate-limit');
const auth = require('../middlewares/auth');
const validate = require('../middlewares/validate');
const authRoutes = require('../modules/auth/auth.routes');
const authController = require('../modules/auth/auth.controller');
const { updateMyProfileSchema, changeMyPasswordSchema } = require('../modules/auth/auth.schemas');
const dashboardRoutes = require('../modules/dashboard/dashboard.routes');
const adminUserRoutes = require('../modules/admins/admin.routes');
const roleRoutes = require('../modules/roles/role.routes');
const permissionRoutes = require('../modules/permissions/permission.routes');
const imageConfigRoutes = require('../modules/image-configs/imageConfig.routes');
const panelSettingRoutes = require('../modules/panel-settings/panelSetting.routes');
const smsSettingRoutes = require('../modules/sms-settings/smsSetting.routes');
const uploadRoutes = require('../modules/uploads/upload.routes');
const languageRoutes = require('../modules/languages/language.routes');
const slideshowRoutes = require('../modules/slideshows/slideshow.routes');
const onboardingPageRoutes = require('../modules/onboarding-pages/onboardingPage.routes');
const contentPageRoutes = require('../modules/content-pages/contentPage.routes');
const blogPostRoutes = require('../modules/blog-posts/blogPost.routes');
const faqCategoryRoutes = require('../modules/faq-categories/faqCategory.routes');
const faqRoutes = require('../modules/faqs/faq.routes');
const contactPageRoutes = require('../modules/contact-page/contactPage.routes');
const bannerRoutes = require('../modules/banners/banner.routes');
const serviceTypeRoutes = require('../modules/service-types/serviceType.routes');
const attributeGroupRoutes = require('../modules/attribute-groups/attributeGroup.routes');
const locationRoutes = require('../modules/locations/location.routes');
const businessRoutes = require('../modules/businesses/business.routes');
const businessUserRoutes = require('../modules/business-users/businessUser.routes');
const appUserRoutes = require('../modules/app-users/appUser.routes');
const appWalletRoutes = require('../modules/app-wallets/appWallet.routes');
const classifiedCategoryRoutes = require('../modules/classified-categories/classifiedCategory.routes');
const classifiedAttributeRoutes = require('../modules/classified-attributes/classifiedAttribute.routes');
const classifiedAdAdminRoutes = require('../modules/classified-ads-admin/classifiedAdAdmin.routes');
const classifiedReportRoutes = require('../modules/classified-reports/classifiedReport.routes');
const classifiedOperationRoutes = require('../modules/classified-operations/classifiedOperation.routes');
const classifiedChatAdminRoutes = require('../modules/classified-chats-admin/classifiedChatAdmin.routes');
const eventCategoryRoutes = require('../modules/event-categories/eventCategory.routes');
const eventRoutes = require('../modules/events/event.routes');
const businessRoleRoutes = require('../modules/business-roles/businessRole.routes');
const businessWorkingHourRoutes = require('../modules/business-working-hours/businessWorkingHour.routes');
const businessContactLinkRoutes = require('../modules/business-contact-links/businessContactLink.routes');
const offeringCategoryRoutes = require('../modules/business-offering-categories/businessOfferingCategory.routes');
const offeringRoutes = require('../modules/business-offerings/businessOffering.routes');
const offeringOptionGroupRoutes = require('../modules/business-offering-option-groups/businessOfferingOptionGroup.routes');
const offeringOptionRoutes = require('../modules/business-offering-options/businessOfferingOption.routes');
const businessOfferRoutes = require('../modules/business-offers/businessOffer.routes');
const auditLogRoutes = require('../modules/audit-logs/auditLog.routes');
const errorLogRoutes = require('../modules/error-logs/errorLog.routes');
const menuRoutes = require('../modules/menu/menu.routes');

const router = express.Router();

const authRateLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 50,
  standardHeaders: true,
  legacyHeaders: false
});

router.use('/auth', authRateLimiter, authRoutes);
router.get('/me', auth, authController.me);
router.patch('/me/profile', auth, validate(updateMyProfileSchema), authController.updateMyProfile);
router.patch('/me/password', auth, validate(changeMyPasswordSchema), authController.changeMyPassword);
router.use('/dashboard', dashboardRoutes);
router.use('/admins', adminUserRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/image-configs', imageConfigRoutes);
router.use('/panel-settings', panelSettingRoutes);
router.use('/sms-settings', smsSettingRoutes);
router.use('/uploads', uploadRoutes);
router.use('/languages', languageRoutes);
router.use('/slideshows', slideshowRoutes);
router.use('/onboarding-pages', onboardingPageRoutes);
router.use('/content-pages', contentPageRoutes);
router.use('/blog-posts', blogPostRoutes);
router.use('/faq-categories', faqCategoryRoutes);
router.use('/faqs', faqRoutes);
router.use('/contact-page', contactPageRoutes);
router.use('/banners', bannerRoutes);
router.use('/service-types', serviceTypeRoutes);
router.use('/attribute-groups', attributeGroupRoutes);
router.use('/locations', locationRoutes);
router.use('/businesses', businessRoutes);
router.use('/business-users', businessUserRoutes);
router.use('/app-users', appUserRoutes);
router.use('/app-wallets', appWalletRoutes);
router.use('/classified-categories', classifiedCategoryRoutes);
router.use('/classified-attributes', classifiedAttributeRoutes);
router.use('/classified-ads', classifiedAdAdminRoutes);
router.use('/classified-reports', classifiedReportRoutes);
router.use('/classified-operations', classifiedOperationRoutes);
router.use('/classified-chats', classifiedChatAdminRoutes);
router.use('/event-categories', eventCategoryRoutes);
router.use('/events', eventRoutes);
router.use('/business-roles', businessRoleRoutes);
router.use('/business-working-hours', businessWorkingHourRoutes);
router.use('/business-contact-links', businessContactLinkRoutes);
router.use('/offering-categories', offeringCategoryRoutes);
router.use('/offerings', offeringRoutes);
router.use('/offering-option-groups', offeringOptionGroupRoutes);
router.use('/offering-options', offeringOptionRoutes);
router.use('/business-offers', businessOfferRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/error-logs', errorLogRoutes);
router.use('/menu', menuRoutes);

module.exports = router;

